Update PKGBUILD.bolt
- this still fails with:

-> Converting perf data to BOLT format...
BOLT-INFO: shared object or position-independent executable detected
PERF2BOLT: Starting data aggregation job for /tmp/makepkg/glibc/src/glibc-build/perf.data
PERF2BOLT: spawning perf job to read branch events
PERF2BOLT: spawning perf job to read mem events
PERF2BOLT: spawning perf job to read process events
PERF2BOLT: spawning perf job to read task events
BOLT-INFO: Target architecture: x86_64
BOLT-INFO: BOLT version: 8ff4d27fe6b32ea1a127758c121cc2a980439833
BOLT-INFO: first alloc address is 0x0
BOLT-INFO: creating new program header table at address 0x400000, offset 0x400000
BOLT-INFO: enabling relocation mode
BOLT-INFO: enabling strict relocation mode for aggregation purposes
BOLT-ERROR: function __restore_rt/1 is in conflict with FDE [44d0f, 44d19). Skipping.
BOLT-WARNING: sizes differ for function __setcontext/1. FDE : 125; symbol table : 145. Using max size.
BOLT-WARNING: sizes differ for function setcontext. FDE : 125; symbol table : 145. Using max size.
BOLT-WARNING: sizes differ for function __GI___clone/1. FDE : 48; symbol table : 91. Using max size.
BOLT-WARNING: sizes differ for function clone. FDE : 48; symbol table : 91. Using max size.
BOLT-WARNING: sizes differ for function __clone. FDE : 48; symbol table : 91. Using max size.
BOLT-WARNING: sizes differ for function __clone3/1. FDE : 23; symbol table : 67. Using max size.
BOLT-WARNING: sizes differ for function __GI___clone3/1. FDE : 23; symbol table : 67. Using max size.
BOLT-WARNING: FDE [0x4bffd, 0x4c011) conflicts with function __setcontext/1(*2)
BOLT-WARNING: FDE [0x15db4a, 0x15db5a) conflicts with function __GI___clone/1(*3)
BOLT-WARNING: FDE [0x15db5a, 0x15db6b) conflicts with function __GI___clone/1(*3)
BOLT-WARNING: FDE [0x15dcf1, 0x15dd02) conflicts with function __clone3/1(*2)
BOLT-WARNING: FDE [0x15dd02, 0x15dd13) conflicts with function __clone3/1(*2)
BOLT-ERROR: symbol seen in the middle of the function __BOLT_FDE_FUNCat44d0f. Skipping.
BOLT-INFO: pre-processing profile using perf data aggregator
BOLT-INFO: binary build-id is:     114af59be32e173aebc91d1212b6d573cff85def
PERF2BOLT: spawning perf job to read buildid list
PERF2BOLT: matched build-id and file name
PERF2BOLT: waiting for perf mmap events collection to finish...
PERF2BOLT: parsing perf-script mmap events output
PERF2BOLT: waiting for perf task events collection to finish...
PERF2BOLT: parsing perf-script task events output
PERF2BOLT: input binary is associated with 82 PID(s)
PERF2BOLT: waiting for perf events collection to finish...
PERF2BOLT: parse branch events...
PERF2BOLT: read 15016 samples and 406421 LBR entries
PERF2BOLT: 0 samples (0.0%) were ignored
PERF2BOLT: traces mismatching disassembled function contents: 33 (0.0%)
PERF2BOLT: out of range traces involving unknown regions: 369864 (94.2%)
PERF2BOLT: waiting for perf mem events collection to finish...
BOLT-INFO: forcing -jump-tables=move as PIC jump table was detected in function iconv
BOLT-WARNING: reference in the middle of instruction detected in function ____wcstof_l_internal/1 at offset 0x1500
BOLT-ERROR: cannot find BB containing branch destination.
FATAL BOLT-ERROR: =======================================
BOLT is unable to proceed because it couldn't properly understand this function.
If you are running the most recent version of BOLT, you may want to report this and paste this dump.
Please check that there is no sensitive contents being shared in this dump.

Offending function: ____longjmp_chk/1

Function contents (
  0000: 4C8B4730 4C8B4F08 488B5738 49C1C811  |L.G0L.O.H.W8I...|
  0010: 644C3304 25300000 0049C1C9 11644C33  |dL3.%0...I...dL3|
  0020: 0C253000 000048C1 CA116448 33142530  |.%0...H...dH3.%0|
  0030: 0000004C 39C4764D 4989FA89 F331FF48  |...L9.vMI....1.H|
  0040: 8D7424E8 B8830000 000F0585 C07531F7  |.t$..........u1.|
  0050: 4424F001 00000074 14488B44 24E84803  |D$.....t.H.D$.H.|
  0060: 4424F84C 29C0483B 4424F873 134883EC  |D$.L).H;D$.s.H..|
  0070: 08488D3D 399D0900 E8930F00 00050505  |.H.=9...........|
  0080: 4C89D789 DE488B1F 4C8B6710 4C8B6F18  |L....H..L.g.L.o.|
  0090: 4C8B7720 4C8B7F28 89F04C89 C44C89CD  |L.w L..(..L..L..|
  00A0: FFE2662E 0F1F8400 00000000 0F1F4000  |..f...........@.|
)

Binary Function "____longjmp_chk/1"  {
  Number      : 2445
  State       : disassembled
  Address     : 0x16bb50
  Size        : 0xa2
  MaxSize     : 0xb0
  Offset      : 0x16bb50
  Section     : .text
  Orc Section : .local.text.____longjmp_chk/1
  LSDA        : 0x0
  IsSimple    : 1
  IsMultiEntry: 0
  IsSplit     : 0
  BB Count    : 6
  CFI Instrs  : 16
}
DWARF CFI Instructions:
    0000003b:   OpRegister Reg5 Reg10
    0000003d:   OpRegister Reg4 Reg3
    00000071:   OpRememberState
    00000071:   OpDefCfaOffset 16
    0000007d:   OpRestoreState
    00000083:   OpRestore Reg5
    00000085:   OpRestore Reg4
    00000085:   OpDefCfa Reg5 0
    00000085:   OpRegister Reg7 Reg8
    00000085:   OpRegister Reg6 Reg9
    00000085:   OpRegister Reg16 Reg1
    00000085:   OpOffset Reg3 0
    00000085:   OpOffset Reg12 16
    00000085:   OpOffset Reg13 24
    00000085:   OpOffset Reg14 32
    00000085:   OpOffset Reg15 40
End of Function "____longjmp_chk/1"

ERROR: disassembly failed - inconsistent branch found.
=======================================

LLVM ERROR: pthread_join failed: Resource deadlock avoided
 #0 0x000063639381ab05 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) Signals.cpp:0:0
 #1 0x000063639381aef5 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
 #2 0x000063638ebfad10 __restore_rt libc_sigaction.c:0:0
 #3 0x000063638ec6b60d pthread_kill@@GLIBC_2.34 (/tmp/makepkg/glibc/src/tmp-root/usr/lib/libc.so.6+0xb560d)
 #4 0x000063638ebfabf2 gsignal (/tmp/makepkg/glibc/src/tmp-root/usr/lib/libc.so.6+0x44bf2)
 #5 0x000063638ebda437 abort (/tmp/makepkg/glibc/src/tmp-root/usr/lib/libc.so.6+0x24437)
 #6 0x00006363937fa422 llvm::report_fatal_error(llvm::Twine const&, bool) (/home/marcus/llvm21/bin/llvm-bolt+0x1dfa422)
 #7 0x000063639381b6ab (/home/marcus/llvm21/bin/llvm-bolt+0x1e1b6ab)
 #8 0x0000636393201dfc (/home/marcus/llvm21/bin/llvm-bolt+0x1801dfc)
 #9 0x0000636393201d53 llvm::StdThreadPool::~StdThreadPool() (/home/marcus/llvm21/bin/llvm-bolt+0x1801d53)
#10 0x0000636393ec8049 llvm::StdThreadPool::~StdThreadPool() (/home/marcus/llvm21/bin/llvm-bolt+0x24c8049)
#11 0x0000636393ec5612 std::unique_ptr<llvm::ThreadPoolInterface, std::default_delete<llvm::ThreadPoolInterface>>::~unique_ptr() ParallelUtilities.cpp:0:0
#12 0x000063638ebfd8a2 __run_exit_handlers (/tmp/makepkg/glibc/src/tmp-root/usr/lib/libc.so.6+0x478a2)
#13 0x000063638ebfd99a (/tmp/makepkg/glibc/src/tmp-root/usr/lib/libc.so.6+0x4799a)
#14 0x00006363939097be std::_Function_handler<void (llvm::bolt::BinaryFunction&, unsigned short), llvm::bolt::RewriteInstance::buildFunctionsCFG()::$_0>::_M_invoke(std::_Any_data const&, llvm::bolt::BinaryFunction&, unsigned short&&) RewriteInstance.cpp:0:0
#15 0x0000636393ec72a4 std::_Function_handler<void (), std::_Bind<llvm::bolt::ParallelUtilities::runOnEachFunctionWithUniqueAllocId(llvm::bolt::BinaryContext&, llvm::bolt::ParallelUtilities::SchedulingPolicy, std::function<void (llvm::bolt::BinaryFunction&, unsigned short)>, std::function<bool (llvm::bolt::BinaryFunction const&)>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, bool, unsigned int)::$_0 (std::_Rb_tree_iterator<std::pair<unsigned long const, llvm::bolt::BinaryFunction>>, std::_Rb_tree_iterator<std::pair<unsigned long const, llvm::bolt::BinaryFunction>>, unsigned int)>>::_M_invoke(std::_Any_data const&) ParallelUtilities.cpp:0:0
#16 0x0000636393954098 std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<std::function<void ()>>>, void>>::_M_invoke(std::_Any_data const&) DWARFRewriter.cpp:0:0
#17 0x00006363938ae2c1 std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) JITLinkLinker.cpp:0:0
#18 0x000063638ec6ecf7 __pthread_once_slow.isra.0 pthread_once.c:0:0
#19 0x000063638ec6ed99 __pthread_once@GLIBC_2.2.5 (/tmp/makepkg/glibc/src/tmp-root/usr/lib/libc.so.6+0xb8d99)
#20 0x0000636393201540 void std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) JITLinkLinker.cpp:0:0
#21 0x0000636393201491 std::__future_base::_State_baseV2::_M_set_result(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool) JITLinkLinker.cpp:0:0
#22 0x000063639320141a std::__future_base::_Deferred_state<std::thread::_Invoker<std::tuple<std::function<void ()>>>, void>::_M_complete_async() DWARFRewriter.cpp:0:0
#23 0x00006363931e860d std::__future_base::_State_baseV2::wait() DWARFRewriter.cpp:0:0
#24 0x0000636393201856 llvm::StdThreadPool::processTasks(llvm::ThreadPoolTaskGroup*) ThreadPool.cpp:0:0
#25 0x00006363932015e3 void* llvm::thread::ThreadProxy<std::tuple<llvm::StdThreadPool::grow(int)::$_0>>(void*) ThreadPool.cpp:0:0
#26 0x000063638ec6951c start_thread pthread_create.c:0:0
#27 0x000063638ed13cf8 __GI___clone3 (/tmp/makepkg/glibc/src/tmp-root/usr/lib/libc.so.6+0x15dcf8)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.